---
port: 4000
host: 0.0.0.0
safe: false

exclude: [README.md, .gitignore, sp, tmparchive, LICENSE]
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title:       "Workshop on Automatic Simultaneous Translation (AutoSimTrans)"
keywords:    "workshop, machine translation, natural language processing"
description: "The official website for the Workshop on Automatic Simultaneous Translation"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"

collections:
  - pages_2020
  #- pages_2018
  #- pages_2020_rc

theme: jekyll-theme-tactile